name: PSMDevTools
main: PSMDevTools\DevTools
version: 1.12.5
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
load: POSTWORLD
authors: [PocketMine Team, PMT Team]
description: Helps develop and distribute PocketMine-MP plugins. Modification to implement PSM api to help develop and compile plugins.
website: https://github.com/pmt-mcpe-fun/PSM-DevTools
commands:
 makeserver:
  description: Creates a PocketMine-MP Phar
  usage: "/makeserver"
  permission: devtools.command.makeserver
 makeplugin:
  description: Creates a Phar plugin from one in source code form
  usage: "/makeplugin <pluginName>"
  permission: devtools.command.makeplugin
 checkperm:
  description: Checks a permission value for the current sender, or a player
  usage: "/checkperm <node> [playerName]"
  permission: "devtools.command.checkperm;devtools.command.checkperm.other"
permissions:
 devtools:
  default: op
  description: "Allows using all the DevTools things"
  children:
   devtools.command:
    default: op
    description: "Allows using all the DevTools commands"
    children:
     devtools.command.makeplugin:
      default: op
      description: "Allows the creation of Phar plugins"
     devtools.command.extractplugin:
      default: op
      description: "Allows the extraction of Phar plugins"
     devtools.command.makeserver:
      default: op
      description: "Allows the creation of a PocketMine-MP Phar"
     devtools.command.checkperm:
      default: true
      description: "Allows checking a permission value"
      children:
       devtools.command.checkperm.other:
        default: op
        description: "Allows checking others permission value"
     devtools.command.genplugin:
      default: op
      description: "Allows the user to generate skeleton files for a plugin"

psmimplements: true